[DO NOT MERGE] feat(address): add reservations_google_maps_address to getAddress
tillhub/schemas pull request #1016
Opened 2024-12-19 14:39 UTC by daemyn

Suggestions/Notes: 
- reservations_google_maps_address should not belong to the base address in the first place (it's a field used in a specific case and only for branches)
- The main issue now is that it's conflicting with delivery_notes that read address from branch, and when this field exists, it fails the validation as `additionalProperties: false`
- This PR is currently a draft and is treated as POC for now

2025-01-06 16:25 UTC, alghanor commented
@daemyn I think we should also remove all other custom address objects and have a single reference only

2025-01-06 18:49 UTC, alghanor requested changes
I think we need to make sure that there is only one address schema and that it has optional fields for e.g. google maps

2025-01-14 16:32 UTC, mohsen89z commented on lib/common/address.js
> +          }
Could you please use oneOf as a helper utility? it's already imported to this file too.

2025-01-15 08:46 UTC, alghanor commented
my idea: https://github.com/tillhub/schemas/pull/1020 @mohsen89z @daemyn @mdovhopo

2025-03-01 14:27 UTC, alghanor commented
https://github.com/tillhub/schemas/pull/1020

2025-03-01 14:27 UTC, closed without merging