feat: signing configuration for fiskaly
tillhub/schemas pull request #467
Opened 2020-08-27 21:40 UTC by 23RoMax

Storing the necessary values for the fiskaly backend

2020-08-27 22:43 UTC, alghanor commented on lib/v1/configurations/items/transactions.js
> +        configuration: {
should be something like fiscally_api

2020-08-27 22:44 UTC, alghanor requested changes
naming, maybe clarify

2020-08-27 23:32 UTC, alghanor requested changes
it seems that in this context signing by itself should be optional, also the existing properties

2020-08-29 13:05 UTC, 23RoMax commented on lib/v1/configurations/items/transactions.js
> +        configuration: {
@alghanor We expect the configuration to be independent from the API that it will be handling. Thus the oneOf.
There can be a second config later to give other systems more control. Does it makes sense to you?

2020-08-31 13:32 UTC, alghanor commented on lib/v1/configurations/items/transactions.js
> +        configuration: {
I recommend doing this only if they will have a big overlap (e.g. if they all have organization_id and api_key) ... 
- if this is the case then I still recommend naming it 'api' (everything here is 'configuration' already)
- if not then this could easily be several new object-fields (fiskaly, fiskaltrust)

2020-08-31 13:34 UTC, alghanor commented on lib/v1/configurations/items/transactions.js
> +              description: 'Fiskaly configuration: Organization id, api key, and api secret',
this is where the description would be misleading in case one sets type to tse_epson

2020-08-31 13:35 UTC, alghanor requested changes
new comments

2021-04-27 21:16 UTC, alghanor commented
outdated, covered by signing.type + singing.resource_type

2021-04-27 21:16 UTC, closed without merging