feat(big-query): Realign transaction v1 legacy schema
tillhub/schemas pull request #494
Opened 2020-10-21 08:25 UTC by eytand

2020-10-21 20:59 UTC, alghanor commented on lib/v1/transactions/legacy/base.js
> -  temp_staff: {
this is used and should stay... hard to tell if this ever happens (but in theory it's possible)

2020-10-21 21:02 UTC, alghanor commented on lib/v1/transactions/legacy/base.js
> +          fr_transaction_id: {
I thought this is just [name: value], fr_transaction_id is not used from our side

2020-10-21 21:03 UTC, alghanor commented on lib/v1/transactions/legacy/base.js
> -  _temporary_staff: oneOf({
should stay... is meant to replace temporary_staff

2020-10-21 21:04 UTC, alghanor commented on lib/v1/transactions/legacy/base.js
> -  branch: oneOf({
should stay... not sure if a register can ever switch to another branch... but who knows?

2020-10-21 21:09 UTC, alghanor commented on lib/v1/transactions/legacy/items/base.js
> -          order: oneOf({
this must stay.. it belongs to discounts -> txCiDiscounts

2020-10-21 21:10 UTC, alghanor commented on lib/v1/transactions/legacy/items/base.js
> -          vat_rate_class: oneOf({
yes, this does not belong to discounts

2020-10-21 21:10 UTC, alghanor requested changes
see comments

2020-10-22 09:37 UTC, alghanor commented on lib/v1/transactions/legacy/base.js
> +      type: 'number',
must be INT

2020-10-22 09:38 UTC, alghanor commented on lib/v1/transactions/legacy/items/base.js
> +      type: 'number',
must be INT

2020-10-22 09:43 UTC, alghanor requested changes
see comments

2020-10-22 09:43 UTC, alghanor commented on lib/v1/transactions/legacy/items/base.js
> +      type: 'number',
must be INT

2020-10-22 09:43 UTC, alghanor commented on lib/v1/transactions/legacy/items/base.js
> +      type: 'number',
must be INT

2020-10-22 09:43 UTC, alghanor commented on lib/v1/transactions/legacy/items/base.js
> +      type: 'number',
must be INT

2020-10-22 09:43 UTC, alghanor commented on lib/v1/transactions/legacy/items/base.js
> +      type: 'number',
must be INT

2020-10-22 09:43 UTC, alghanor commented on lib/v1/transactions/legacy/items/base.js
> +      type: 'integer',
should be BOOL, please verify

2020-10-22 09:43 UTC, alghanor commented on lib/v1/transactions/legacy/items/base.js
> +            type: 'number',
must be INT

2020-10-22 09:43 UTC, alghanor commented on lib/v1/transactions/legacy/items/base.js
> +            type: 'number',
must be INT

2020-10-22 09:43 UTC, alghanor commented on lib/v1/transactions/legacy/payments/base.js
> +      type: 'number',
must be INT

2020-10-22 09:43 UTC, alghanor commented on lib/v1/transactions/legacy/payments/base.js
> +      type: 'number',
must be INT

2020-10-27 15:56 UTC, eytand reviewed
@alghanor fixed according to your comments

2020-10-27 15:56 UTC, eytand commented on lib/v1/transactions/legacy/base.js
> +      type: 'number',
fixed

2020-10-27 15:56 UTC, eytand commented on lib/v1/transactions/legacy/base.js
> +          fr_transaction_id: {
removed

2020-10-27 15:56 UTC, eytand commented on lib/v1/transactions/legacy/items/base.js
> +      type: 'number',
fixed

2020-10-27 15:56 UTC, eytand commented on lib/v1/transactions/legacy/items/base.js
> +      type: 'number',
fixed

2020-10-27 15:56 UTC, eytand commented on lib/v1/transactions/legacy/items/base.js
> +      type: 'number',
fixed

2020-10-27 15:56 UTC, eytand commented on lib/v1/transactions/legacy/items/base.js
> +      type: 'number',
fixed

2020-10-27 15:56 UTC, eytand commented on lib/v1/transactions/legacy/items/base.js
> +      type: 'number',
fixed

2020-10-27 15:56 UTC, eytand commented on lib/v1/transactions/legacy/items/base.js
> +            type: 'number',
fixed

2020-10-27 15:56 UTC, eytand commented on lib/v1/transactions/legacy/items/base.js
> +            type: 'number',
fixed

2020-10-27 15:56 UTC, eytand commented on lib/v1/transactions/legacy/payments/base.js
> +      type: 'number',
fixed

2020-10-27 15:56 UTC, eytand commented on lib/v1/transactions/legacy/payments/base.js
> +      type: 'number',
fixed

2020-10-27 15:56 UTC, eytand commented on lib/v1/transactions/legacy/base.js
> -  _temporary_staff: oneOf({
re-adding. The removed items are ignored by the API and never get persisted

2020-10-27 15:56 UTC, eytand commented on lib/v1/transactions/legacy/items/base.js
> -          order: oneOf({
not being persisted

2020-10-27 17:07 UTC, alghanor commented on lib/v1/transactions/legacy/items/base.js
> +          fr_transaction_cartitem_id: oneOf({
this should not be here

2020-10-27 17:08 UTC, alghanor requested changes
fr_transaction_cartitem_id should not be in items.base.context

2020-10-27 18:10 UTC, alghanor approved these changes
approved

2020-10-27 18:10 UTC, merged

2020-10-27 18:12 UTC, eljefedelrodeodeljefe commented
:tada: This PR is included in version 5.92.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@tillhub/schemas)
- [GitHub release](https://github.com/tillhub/schemas/releases/tag/v5.92.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: