feat(balances_v1): legacy
tillhub/schemas pull request #495
Opened 2020-10-26 21:24 UTC by alghanor

reflect current state

https://tillhub.atlassian.net/browse/IOS-2099

2020-11-03 10:55 UTC, alghanor commented on lib/v1/balances/legacy/embedded/expenses/response.js
> +      description: 'The server creation time of this transaction.'
update

2020-11-03 11:35 UTC, barbarafarias requested changes
Generally LGTM added some comments but since this is quite big it would be better if you could test this schema validation with some real data.

2020-11-03 11:35 UTC, barbarafarias commented on lib/v1/balances/legacy/embedded/cash_units/create.request.js
> +  $id: 'https://schemas.tillhub.com/v1/transactions.legacy.create.request.schema.json',
Do you need to validate embedded/cash_units separately or will be part of balances request?
If you need it separately then I suggest you to rename this id, I think it will export different schemas with same id.

2020-11-03 11:35 UTC, barbarafarias commented on lib/v1/balances/legacy/embedded/expenses/create.request.js
> +  $id: 'https://schemas.tillhub.com/v1/transactions.legacy.create.request.schema.json',
Do you need to validate embedded/expenses separately or will be part of balances request?
If you need it separately then I suggest you to rename this id, I think it will export different schemas with same id.

2020-11-03 11:35 UTC, barbarafarias commented on lib/v1/balances/legacy/embedded/payments/create.request.js
> +  $id: 'https://schemas.tillhub.com/v1/transactions.legacy.create.request.schema.json',
Do you need to validate embedded/payments separately or will be part of balances request?
If you need it separately then I suggest you to rename this id, I think it will export different schemas with same id.

2020-11-03 11:35 UTC, barbarafarias commented on lib/v1/balances/legacy/embedded/revenues/create.request.js
> +  $id: 'https://schemas.tillhub.com/v1/transactions.legacy.create.request.schema.json',
Do you need to validate embedded/revenues separately or will be part of balances request?
If you need it separately then I suggest you to rename this id, I think it will export different schemas with same id.

2020-11-03 11:35 UTC, barbarafarias commented on lib/v1/balances/legacy/embedded/tips/create.request.js
> +  $id: 'https://schemas.tillhub.com/v1/transactions.legacy.create.request.schema.json',
Do you need to validate embedded/tips separately or will be part of balances request?
If you need it separately then I suggest you to rename this id, I think it will export different schemas with same id.

2020-11-03 11:35 UTC, barbarafarias commented on lib/v1/balances/legacy/embedded/vats/create.request.js
> +  $id: 'https://schemas.tillhub.com/v1/transactions.legacy.create.request.schema.json',
Do you need to validate embedded/vats separately or will be part of balances request?
If you need it separately then I suggest you to rename this id, I think it will export different schemas with same id.

2020-11-03 11:35 UTC, barbarafarias commented on lib/v1/balances/legacy/create.request.js
> +  $id: 'https://schemas.tillhub.com/v1/transactions.legacy.create.request.schema.json',
Shouldn't it be called https://schemas.tillhub.com/v1/balances.legacy.create.request.schema.json ?

2020-11-07 12:19 UTC, 23RoMax commented on lib/v1/balances/legacy/base.js
> +      description: 'Initialized as the iPAD\'s UIDevice.current.identifierForVendor?.uuidString.md5() and stored in the Keychain for the Tillhub application'
Could be extended for:

MachineGuid (win) or IOPlatformUUID (mac) in electron pos

2020-11-07 12:20 UTC, 23RoMax commented on lib/v1/balances/legacy/base.js
> +      description: 'The balance\'s counting number'
description: 'The balance\'s counting number. A sequential counter that may be reset in error cases'

2020-11-09 17:52 UTC, merged

2020-11-09 17:54 UTC, eljefedelrodeodeljefe commented
:tada: This PR is included in version 5.99.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@tillhub/schemas)
- [GitHub release](https://github.com/tillhub/schemas/releases/tag/v5.99.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: