Draft API-636
tillhub/schemas pull request #548
Opened 2021-05-10 13:30 UTC by leolara

2021-05-21 09:14 UTC, aleksey-a-maltsev requested changes

2021-05-21 09:14 UTC, aleksey-a-maltsev commented on lib/v0/table_layouts/index.js
> +  upsert: {
We're usually use create + update + get. Do we really need upsert? Plus upsert should cover create as well.

2021-05-21 10:33 UTC, leolara commented on lib/v0/table_layouts/index.js
> +  upsert: {
https://stackoverflow.com/questions/18470588/in-rest-is-post-or-put-best-suited-for-upsert-operation

2021-05-21 12:45 UTC, merged

2021-05-26 20:16 UTC, eljefedelrodeodeljefe commented
:tada: This PR is included in version 6.38.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@tillhub/schemas)
- [GitHub release](https://github.com/tillhub/schemas/releases/tag/v6.38.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: