feat(configurations): balances
tillhub/schemas pull request #592
Opened 2021-08-02 09:51 UTC by alghanor

add toggle for expense grouping

https://tillhub.atlassian.net/browse/IOS-2502

2021-08-02 11:48 UTC, boris-savic requested changes

2021-08-02 11:48 UTC, boris-savic commented on lib/v1/configurations/items/balances.js
> +      default: false
Shouldn't this be by default true? Since currently we group them? Or am I missing something?

2021-08-02 12:13 UTC, alghanor commented on lib/v1/configurations/items/balances.js
> +      default: false
currently only the total is shown/printed

2021-08-04 20:31 UTC, boris-savic approved these changes

2021-08-10 10:52 UTC, merged

2021-08-10 10:54 UTC, eljefedelrodeodeljefe commented
:tada: This PR is included in version 6.76.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@tillhub/schemas)
- [GitHub release](https://github.com/tillhub/schemas/releases/tag/v6.76.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: