feat(loyalties-abocard-systems): add abocard systems schema #API-1017
tillhub/schemas pull request #616
Opened 2021-09-15 15:49 UTC by aleksey-a-maltsev

2021-09-15 16:38 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +    type: 'object',
would prefer just string (uuid of the voucher system)

2021-09-15 16:38 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'The price of the product being used',
what does that mean?

2021-09-15 16:39 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'The price source',
what does that mean?

2021-09-15 16:39 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'The price ID',
what does that mean?

2021-09-15 16:40 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'The selling price',
so far this is the price being used on the 'sell'-action ... shouldn't some properties then also be moved there?

2021-09-15 16:42 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'The amount of units',
is this the number of vouchers being issued on the sell-action?

2021-09-15 16:45 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +  voucher_value_per_unit: oneOf({
if I understood this correctly - then those 'per_unit_xyz' overdetermine the system - also this gives the impression that a full system can just be good for a single use-case?

2021-09-15 16:46 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +      description: 'The product associated with this action',
basically the full aboard, right?

2021-09-15 16:46 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'Referenced product',
the 'to-be-discounted' product on the N vouchers issued?

2021-09-15 16:47 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +  system_revenue_account: oneOf({
wouldn't this be covered by the actions (abocard)-product?

2021-09-15 16:49 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +      ...voucherSystemProperties
is the reference not sufficient?

2021-09-15 16:50 UTC, alghanor requested changes
needs some discussion and improvements of the comments mainly

2021-09-16 06:12 UTC, aleksey-a-maltsev commented on lib/v0/loyalty_abocard_systems/base.js
> +    type: 'object',
We have to send the voucher system data as well while create/update (when `system_type = 'voucher'`). We can use 2 different fields but I don't see any sense for it.

2021-09-16 06:15 UTC, aleksey-a-maltsev commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'The price of the product being used',
Better to ask Max. AFAIR this is the price of the product we use to sell in context of abocard. If you have better variant just write it here, my English just not good enough :)

2021-09-16 06:45 UTC, aleksey-a-maltsev commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'The price source',
Details added

2021-09-16 06:46 UTC, aleksey-a-maltsev commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'The price ID',
Details added

2021-09-16 06:48 UTC, aleksey-a-maltsev commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'The selling price',
Do you have particular example? Also better clarify with @23RoMax

2021-09-16 06:50 UTC, aleksey-a-maltsev commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'The total value',
@23RoMax please help with better decription here.

2021-09-16 06:50 UTC, aleksey-a-maltsev commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'The amount of units',
I think it's number of abocrads.

2021-09-16 06:53 UTC, aleksey-a-maltsev commented on lib/v0/loyalty_abocard_systems/base.js
> +  voucher_value_per_unit: oneOf({
Better clarify with @23RoMax

2021-09-16 06:57 UTC, aleksey-a-maltsev commented on lib/v0/loyalty_abocard_systems/base.js
> +      description: 'The product associated with this action',
This product creates automatically on abocard system creation based on `linked_product`.

2021-09-16 07:01 UTC, aleksey-a-maltsev commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'Referenced product',
Product liked to abocard system. New products being created for `abocard.actions` and `voucher_system.product` based on this value.

2021-09-16 07:08 UTC, aleksey-a-maltsev commented on lib/v0/loyalty_abocard_systems/base.js
> +  system_revenue_account: oneOf({
It uses for new product which appears in `actions`.

2021-09-16 07:09 UTC, aleksey-a-maltsev commented on lib/v0/loyalty_abocard_systems/base.js
> +      ...voucherSystemProperties
Why? It defines schema for case system_type = 'voucher'

2021-09-16 09:11 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +      ...voucherSystemProperties
this was about id vs id + all data

2021-09-16 09:13 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'The amount of units',
now I am even more confused

2021-09-16 10:14 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'Product liked to abocard system. New products being created for "actions[...].product" and "voucher_system.product" based on this value (VAT ID reference is most important part).',
typo 'liked'

2021-09-16 10:21 UTC, 23RoMax commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'The price of the product being used',
@alghanor The dashboard requires to know the price on which the calculation takes place. This is going to be the uuid of the price selected by the user on which the whole scheme is getting calculated. Has no use for POS.

2021-09-16 10:21 UTC, 23RoMax commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'The selling price',
Exactly, that's the price the abocard gets sold for.
What do you mean by `shouldn't some properties then also be moved there?` ?

2021-09-16 10:21 UTC, 23RoMax commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'The amount of units',
It's the amount of vouchers that we issue on creation of the abocard. @alghanor 

@aleksey-a-maltsev not the amount of products or something like that.

2021-09-16 10:21 UTC, 23RoMax commented on lib/v0/loyalty_abocard_systems/base.js
> +  voucher_value_per_unit: oneOf({
This is part of the configuration of the abocard system of type vouchers.
In case there will be other systems, the abocard system will require extension.

I'm failing to see the point you are trying to make @alghanor. Can you elaborate?

2021-09-16 10:21 UTC, 23RoMax commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'Product liked to abocard system. New products being created for "actions[...].product" and "voucher_system.product" based on this value (VAT ID reference is most important part).',
test

2021-09-16 10:24 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +    type: 'object',
can be done but does not follow the style in use

2021-09-16 10:27 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'The selling price',
to the sell-action

2021-09-16 10:53 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'The amount of units',
then it is obviously prone to misunderstandings

2021-09-16 11:09 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +  voucher_value_per_unit: oneOf({
i understood voucher_value_per_unit * units = total_value ... since all 3 values are present here, none of them are flexible

2021-09-16 12:07 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +  system_revenue_account: oneOf({
system_revenue_account

2021-09-16 12:11 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +    description: 'The price of the product being used',
@23RoMax then it conflicts with this being defined as 'number' (12.99)

2021-09-17 08:11 UTC, aleksey-a-maltsev commented on lib/v0/loyalty_abocard_systems/base.js
> +      ...voucherSystemProperties
I don't get it. All data doesn't contain `id` but `id` is required for update operation.

2021-09-17 09:25 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +      ...voucherSystemProperties
if I have id I can fetch the system and get all it's data

2021-09-17 09:39 UTC, alghanor commented on lib/v0/loyalty_abocard_systems/base.js
> +  system_revenue_account: oneOf({
@23RoMax if you need revenue account information then you must also need tax/vat account information

2021-09-17 10:03 UTC, alghanor approved these changes
approved with concerns

2021-09-17 10:03 UTC, merged

2021-09-17 10:05 UTC, eljefedelrodeodeljefe commented
:tada: This PR is included in version 6.87.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@tillhub/schemas)
- [GitHub release](https://github.com/tillhub/schemas/releases/tag/v6.87.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: