feat(pricelists): schema for new pricelists endpoint
tillhub/schemas pull request #787
Opened 2023-03-17 08:40 UTC by tatiana-sudakova

2023-03-17 09:16 UTC, mohsen89z requested changes
LGTM, some minor changes.
Also, it's missing the changes in [products index](https://github.dev/tillhub/schemas/blob/65d8bd3f2b91ed8735a3ed1758db965403e1a72c/lib/v1/products/index.js)

2023-03-20 13:27 UTC, alghanor commented on lib/v1/products/pricelist/response.js
> +    price_book: oneOf({
@tatiana-sudakova should not be in client response

2023-03-20 13:28 UTC, alghanor commented on lib/v1/products/pricelist/response.js
> +    updated_at: {
@tatiana-sudakova should not be in client response

2023-03-21 16:12 UTC, tatiana-sudakova commented on lib/v1/products/pricelist/response.js
> +    price_book: oneOf({
That was in tech spec, I can remove it.

2023-03-21 16:16 UTC, tatiana-sudakova commented on lib/v1/products/pricelist/response.js
> +    updated_at: {
@alghanor 
Why are you against updated_at field? I think it's necessary for client to check that data they received are newer then the one they have in local cache.

2023-04-18 08:00 UTC, mohsen89z approved these changes

2023-04-18 13:15 UTC, merged

2023-04-18 13:17 UTC, tillhub-engineering commented
:tada: This PR is included in version 6.209.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@tillhub/schemas)
- [GitHub release](https://github.com/tillhub/schemas/releases/tag/v6.209.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: