feat(transactions): external_rewards
tillhub/schemas pull request #826
Opened 2023-07-17 16:31 UTC by alghanor

add schema for coop superpoint delta

https://unz.atlassian.net/browse/UNTIL-7160

draft

2023-07-17 17:56 UTC, alghanor commented on lib/v1/transactions/legacy/base.js
> +  external_rewards: oneOf({
@tatiana-sudakova this could be array, but i doubt there is any use-case - but if you insist?

2023-07-20 17:00 UTC, mohsen89z requested changes
The object schema is correct.
Yet I do like the naming starts with capital letters. This should follow our structure, the name should be the same so mapping would be easier on the cloud function.
 ie. `StoreSapnumber ` should be `store_sap_number`

2023-07-20 18:39 UTC, mohsen89z approved these changes

2023-07-20 18:49 UTC, merged

2023-07-20 18:50 UTC, tillhub-engineering commented
:tada: This PR is included in version 6.233.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@tillhub/schemas)
- [GitHub release](https://github.com/tillhub/schemas/releases/tag/v6.233.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: